# Configure the initial defaults for the collision behavior reflexes.
collision_config:
  # lower_torque_thresholds_acceleration: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
  # upper_torque_thresholds_acceleration: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
  # lower_torque_thresholds_nominal: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
  # upper_torque_thresholds_nominal: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
  # lower_force_thresholds_acceleration: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
  # upper_force_thresholds_acceleration: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
  # lower_force_thresholds_nominal: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
  # upper_force_thresholds_nominal: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
  # lower_torque_thresholds_acceleration: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]  # [Nm]
  # upper_torque_thresholds_acceleration: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]  # [Nm]
  # lower_torque_thresholds_nominal: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]  # [Nm]
  # upper_torque_thresholds_nominal: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]  # [Nm]
  # lower_force_thresholds_acceleration: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]  # [N, N, N, Nm, Nm, Nm]
  # upper_force_thresholds_acceleration: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]  # [N, N, N, Nm, Nm, Nm]
  # lower_force_thresholds_nominal: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]  # [N, N, N, Nm, Nm, Nm]
  # upper_force_thresholds_nominal: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0]  # [N, N, N, Nm, Nm, Nm]
  lower_torque_thresholds_acceleration: [10, 10, 9, 9, 8, 7, 6]  # [Nm]
  upper_torque_thresholds_acceleration: [10, 10, 9, 9, 8, 7, 6]  # [Nm]
  lower_torque_thresholds_nominal: [10, 10, 9, 9, 8, 7, 6]  # [Nm]
  upper_torque_thresholds_nominal: [10, 10, 9, 9, 8, 7, 6]  # [Nm]
  lower_force_thresholds_acceleration: [10, 10, 10, 12, 12, 12]  # [N, N, N, Nm, Nm, Nm]
  upper_force_thresholds_acceleration: [10, 10, 10, 12, 12, 12]  # [N, N, N, Nm, Nm, Nm]
  lower_force_thresholds_nominal: [10, 10, 10, 12, 12, 12]  # [N, N, N, Nm, Nm, Nm]
  upper_force_thresholds_nominal: [10, 10, 10, 12, 12, 12]  # [N, N, N, Nm, Nm, Nm]

joint_limit_warning_threshold: 0.1
realtime_config: enforce