# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hrca_msgs/RobotTaskGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class RobotTaskGoal(genpy.Message):
  _md5sum = "7f2c64fd41eafea32d78342b5e64b8ad"
  _type = "hrca_msgs/RobotTaskGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
string action #'hold', 'pick_and_place', 'move_to_pose', 'move_to_pose_cartesian', 'pick_and_handoff'
geometry_msgs/PoseStamped pose1
geometry_msgs/PoseStamped pose2
string object_name

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['action','pose1','pose2','object_name']
  _slot_types = ['string','geometry_msgs/PoseStamped','geometry_msgs/PoseStamped','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       action,pose1,pose2,object_name

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotTaskGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.action is None:
        self.action = ''
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.PoseStamped()
      if self.pose2 is None:
        self.pose2 = geometry_msgs.msg.PoseStamped()
      if self.object_name is None:
        self.object_name = ''
    else:
      self.action = ''
      self.pose1 = geometry_msgs.msg.PoseStamped()
      self.pose2 = geometry_msgs.msg.PoseStamped()
      self.object_name = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.action
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.pose1.header.seq, _x.pose1.header.stamp.secs, _x.pose1.header.stamp.nsecs))
      _x = self.pose1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.pose1.pose.position.x, _x.pose1.pose.position.y, _x.pose1.pose.position.z, _x.pose1.pose.orientation.x, _x.pose1.pose.orientation.y, _x.pose1.pose.orientation.z, _x.pose1.pose.orientation.w, _x.pose2.header.seq, _x.pose2.header.stamp.secs, _x.pose2.header.stamp.nsecs))
      _x = self.pose2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.pose2.pose.position.x, _x.pose2.pose.position.y, _x.pose2.pose.position.z, _x.pose2.pose.orientation.x, _x.pose2.pose.orientation.y, _x.pose2.pose.orientation.z, _x.pose2.pose.orientation.w))
      _x = self.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.PoseStamped()
      if self.pose2 is None:
        self.pose2 = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.pose1.header.seq, _x.pose1.header.stamp.secs, _x.pose1.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose1.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pose1.pose.position.x, _x.pose1.pose.position.y, _x.pose1.pose.position.z, _x.pose1.pose.orientation.x, _x.pose1.pose.orientation.y, _x.pose1.pose.orientation.z, _x.pose1.pose.orientation.w, _x.pose2.header.seq, _x.pose2.header.stamp.secs, _x.pose2.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose2.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.pose2.pose.position.x, _x.pose2.pose.position.y, _x.pose2.pose.position.z, _x.pose2.pose.orientation.x, _x.pose2.pose.orientation.y, _x.pose2.pose.orientation.z, _x.pose2.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.action
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.pose1.header.seq, _x.pose1.header.stamp.secs, _x.pose1.header.stamp.nsecs))
      _x = self.pose1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.pose1.pose.position.x, _x.pose1.pose.position.y, _x.pose1.pose.position.z, _x.pose1.pose.orientation.x, _x.pose1.pose.orientation.y, _x.pose1.pose.orientation.z, _x.pose1.pose.orientation.w, _x.pose2.header.seq, _x.pose2.header.stamp.secs, _x.pose2.header.stamp.nsecs))
      _x = self.pose2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.pose2.pose.position.x, _x.pose2.pose.position.y, _x.pose2.pose.position.z, _x.pose2.pose.orientation.x, _x.pose2.pose.orientation.y, _x.pose2.pose.orientation.z, _x.pose2.pose.orientation.w))
      _x = self.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.PoseStamped()
      if self.pose2 is None:
        self.pose2 = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.pose1.header.seq, _x.pose1.header.stamp.secs, _x.pose1.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose1.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pose1.pose.position.x, _x.pose1.pose.position.y, _x.pose1.pose.position.z, _x.pose1.pose.orientation.x, _x.pose1.pose.orientation.y, _x.pose1.pose.orientation.z, _x.pose1.pose.orientation.w, _x.pose2.header.seq, _x.pose2.header.stamp.secs, _x.pose2.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose2.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.pose2.pose.position.x, _x.pose2.pose.position.y, _x.pose2.pose.position.z, _x.pose2.pose.orientation.x, _x.pose2.pose.orientation.y, _x.pose2.pose.orientation.z, _x.pose2.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
