// Generated by gencpp from file robohub_object_tracking/TrackedObjectPose.msg
// DO NOT EDIT!


#ifndef ROBOHUB_OBJECT_TRACKING_MESSAGE_TRACKEDOBJECTPOSE_H
#define ROBOHUB_OBJECT_TRACKING_MESSAGE_TRACKEDOBJECTPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace robohub_object_tracking
{
template <class ContainerAllocator>
struct TrackedObjectPose_
{
  typedef TrackedObjectPose_<ContainerAllocator> Type;

  TrackedObjectPose_()
    : id()
    , pose()  {
    }
  TrackedObjectPose_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObjectPose_

typedef ::robohub_object_tracking::TrackedObjectPose_<std::allocator<void> > TrackedObjectPose;

typedef boost::shared_ptr< ::robohub_object_tracking::TrackedObjectPose > TrackedObjectPosePtr;
typedef boost::shared_ptr< ::robohub_object_tracking::TrackedObjectPose const> TrackedObjectPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator1> & lhs, const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator1> & lhs, const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robohub_object_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca24679b18012554617c5552db286b5e";
  }

  static const char* value(const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca24679b18012554ULL;
  static const uint64_t static_value2 = 0x617c5552db286b5eULL;
};

template<class ContainerAllocator>
struct DataType< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robohub_object_tracking/TrackedObjectPose";
  }

  static const char* value(const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Used to hold data for each message. The '...List' message is the one actually used.\n"
"string id\n"
"geometry_msgs/PoseStamped pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObjectPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOHUB_OBJECT_TRACKING_MESSAGE_TRACKEDOBJECTPOSE_H
