// Generated by gencpp from file robohub_object_tracking/TrackedObjectPoseList.msg
// DO NOT EDIT!


#ifndef ROBOHUB_OBJECT_TRACKING_MESSAGE_TRACKEDOBJECTPOSELIST_H
#define ROBOHUB_OBJECT_TRACKING_MESSAGE_TRACKEDOBJECTPOSELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robohub_object_tracking/TrackedObjectPose.h>

namespace robohub_object_tracking
{
template <class ContainerAllocator>
struct TrackedObjectPoseList_
{
  typedef TrackedObjectPoseList_<ContainerAllocator> Type;

  TrackedObjectPoseList_()
    : object_list()  {
    }
  TrackedObjectPoseList_(const ContainerAllocator& _alloc)
    : object_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >::other >  _object_list_type;
  _object_list_type object_list;





  typedef boost::shared_ptr< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObjectPoseList_

typedef ::robohub_object_tracking::TrackedObjectPoseList_<std::allocator<void> > TrackedObjectPoseList;

typedef boost::shared_ptr< ::robohub_object_tracking::TrackedObjectPoseList > TrackedObjectPoseListPtr;
typedef boost::shared_ptr< ::robohub_object_tracking::TrackedObjectPoseList const> TrackedObjectPoseListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator1> & lhs, const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator2> & rhs)
{
  return lhs.object_list == rhs.object_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator1> & lhs, const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robohub_object_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "426728e80dadb19a5b9479f4048ea61c";
  }

  static const char* value(const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x426728e80dadb19aULL;
  static const uint64_t static_value2 = 0x5b9479f4048ea61cULL;
};

template<class ContainerAllocator>
struct DataType< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robohub_object_tracking/TrackedObjectPoseList";
  }

  static const char* value(const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robohub_object_tracking/TrackedObjectPose[] object_list\n"
"================================================================================\n"
"MSG: robohub_object_tracking/TrackedObjectPose\n"
"# Used to hold data for each message. The '...List' message is the one actually used.\n"
"string id\n"
"geometry_msgs/PoseStamped pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObjectPoseList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robohub_object_tracking::TrackedObjectPoseList_<ContainerAllocator>& v)
  {
    s << indent << "object_list[]" << std::endl;
    for (size_t i = 0; i < v.object_list.size(); ++i)
    {
      s << indent << "  object_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robohub_object_tracking::TrackedObjectPose_<ContainerAllocator> >::stream(s, indent + "    ", v.object_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOHUB_OBJECT_TRACKING_MESSAGE_TRACKEDOBJECTPOSELIST_H
