#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/morgan/projects/cws_ws/devel_isolated/orocos_kinematics_dynamics:/home/morgan/projects/cws_ws/devel_isolated/franka_visualization:/home/morgan/projects/cws_ws/devel_isolated/franka_ros_interface:/home/morgan/projects/cws_ws/devel_isolated/franka_ros_controllers:/home/morgan/projects/cws_ws/devel_isolated/franka_ros:/home/morgan/projects/cws_ws/devel_isolated/franka_panda_description:/home/morgan/projects/cws_ws/devel_isolated/franka_interface:/home/morgan/projects/cws_ws/devel_isolated/franka_example_controllers:/home/morgan/projects/cws_ws/devel_isolated/franka_control:/home/morgan/projects/cws_ws/devel_isolated/franka_hw:/home/morgan/projects/cws_ws/devel_isolated/franka_core_msgs:/home/morgan/projects/cws_ws/devel_isolated/franka_msgs:/home/morgan/projects/cws_ws/devel_isolated/franka_gripper:/home/morgan/projects/cws_ws/devel_isolated/franka_description:/home/morgan/projects/cws_ws/devel_isolated/cws_planning:/home/morgan/projects/cws_ws/devel:/opt/ros/melodic:/home/morgan/projects/cws_ws/devel_isolated/orocos_kdl'
export LD_LIBRARY_PATH='/home/morgan/projects/cws_ws/devel_isolated/franka_visualization/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_ros_controllers/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_panda_description/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_interface/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_example_controllers/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_control/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_hw/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_core_msgs/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_msgs/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_gripper/lib:/home/morgan/projects/cws_ws/devel_isolated/franka_description/lib:/home/morgan/projects/cws_ws/devel_isolated/cws_planning/lib:/home/morgan/projects/cws_ws/devel/lib:/opt/ros/melodic/lib:/home/morgan/projects/cws_ws/devel_isolated/orocos_kdl/lib:/home/morgan/projects/cws_ws/devel_isolated/orocos_kdl/lib/x86_64-linux-gnu'
export PATH='/opt/ros/melodic/bin:/home/morgan/projects/cws_ws/devel_isolated/orocos_kdl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin'
export PKG_CONFIG_PATH='/home/morgan/projects/cws_ws/devel_isolated/franka_visualization/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_ros_controllers/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_panda_description/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_interface/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_example_controllers/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_control/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_hw/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_core_msgs/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_msgs/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_gripper/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/franka_description/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/cws_planning/lib/pkgconfig:/home/morgan/projects/cws_ws/devel/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/orocos_kdl/lib/pkgconfig:/home/morgan/projects/cws_ws/devel_isolated/orocos_kdl/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/morgan/projects/cws_ws/devel_isolated/franka_ros_controllers/lib/python2.7/dist-packages:/home/morgan/projects/cws_ws/devel_isolated/franka_interface/lib/python2.7/dist-packages:/home/morgan/projects/cws_ws/devel_isolated/franka_example_controllers/lib/python2.7/dist-packages:/home/morgan/projects/cws_ws/devel_isolated/franka_core_msgs/lib/python2.7/dist-packages:/home/morgan/projects/cws_ws/devel_isolated/franka_msgs/lib/python2.7/dist-packages:/home/morgan/projects/cws_ws/devel_isolated/franka_gripper/lib/python2.7/dist-packages:/home/morgan/projects/cws_ws/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/morgan/projects/cws_ws/devel_isolated/orocos_kdl/lib/python2.7/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/morgan/projects/cws_ws/devel_isolated/orocos_kinematics_dynamics/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/morgan/projects/cws_ws/src/orocos_kinematics_dynamics/orocos_kinematics_dynamics:$ROS_PACKAGE_PATH"