// Generated by gencpp from file hrca_decision/MoveToPosition.msg
// DO NOT EDIT!


#ifndef HRCA_DECISION_MESSAGE_MOVETOPOSITION_H
#define HRCA_DECISION_MESSAGE_MOVETOPOSITION_H

#include <ros/service_traits.h>


#include <hrca_decision/MoveToPositionRequest.h>
#include <hrca_decision/MoveToPositionResponse.h>


namespace hrca_decision
{

struct MoveToPosition
{

typedef MoveToPositionRequest Request;
typedef MoveToPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToPosition
} // namespace hrca_decision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrca_decision::MoveToPosition > {
  static const char* value()
  {
    return "40aca93d2ba3835d16d6b0bb93925874";
  }

  static const char* value(const ::hrca_decision::MoveToPosition&) { return value(); }
};

template<>
struct DataType< ::hrca_decision::MoveToPosition > {
  static const char* value()
  {
    return "hrca_decision/MoveToPosition";
  }

  static const char* value(const ::hrca_decision::MoveToPosition&) { return value(); }
};


// service_traits::MD5Sum< ::hrca_decision::MoveToPositionRequest> should match
// service_traits::MD5Sum< ::hrca_decision::MoveToPosition >
template<>
struct MD5Sum< ::hrca_decision::MoveToPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrca_decision::MoveToPosition >::value();
  }
  static const char* value(const ::hrca_decision::MoveToPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrca_decision::MoveToPositionRequest> should match
// service_traits::DataType< ::hrca_decision::MoveToPosition >
template<>
struct DataType< ::hrca_decision::MoveToPositionRequest>
{
  static const char* value()
  {
    return DataType< ::hrca_decision::MoveToPosition >::value();
  }
  static const char* value(const ::hrca_decision::MoveToPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrca_decision::MoveToPositionResponse> should match
// service_traits::MD5Sum< ::hrca_decision::MoveToPosition >
template<>
struct MD5Sum< ::hrca_decision::MoveToPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrca_decision::MoveToPosition >::value();
  }
  static const char* value(const ::hrca_decision::MoveToPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrca_decision::MoveToPositionResponse> should match
// service_traits::DataType< ::hrca_decision::MoveToPosition >
template<>
struct DataType< ::hrca_decision::MoveToPositionResponse>
{
  static const char* value()
  {
    return DataType< ::hrca_decision::MoveToPosition >::value();
  }
  static const char* value(const ::hrca_decision::MoveToPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRCA_DECISION_MESSAGE_MOVETOPOSITION_H
