// Generated by gencpp from file hrca_decision/MoveBlock.msg
// DO NOT EDIT!


#ifndef HRCA_DECISION_MESSAGE_MOVEBLOCK_H
#define HRCA_DECISION_MESSAGE_MOVEBLOCK_H

#include <ros/service_traits.h>


#include <hrca_decision/MoveBlockRequest.h>
#include <hrca_decision/MoveBlockResponse.h>


namespace hrca_decision
{

struct MoveBlock
{

typedef MoveBlockRequest Request;
typedef MoveBlockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveBlock
} // namespace hrca_decision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrca_decision::MoveBlock > {
  static const char* value()
  {
    return "e344a651812b0bbffc3452f20f9ea415";
  }

  static const char* value(const ::hrca_decision::MoveBlock&) { return value(); }
};

template<>
struct DataType< ::hrca_decision::MoveBlock > {
  static const char* value()
  {
    return "hrca_decision/MoveBlock";
  }

  static const char* value(const ::hrca_decision::MoveBlock&) { return value(); }
};


// service_traits::MD5Sum< ::hrca_decision::MoveBlockRequest> should match
// service_traits::MD5Sum< ::hrca_decision::MoveBlock >
template<>
struct MD5Sum< ::hrca_decision::MoveBlockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrca_decision::MoveBlock >::value();
  }
  static const char* value(const ::hrca_decision::MoveBlockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrca_decision::MoveBlockRequest> should match
// service_traits::DataType< ::hrca_decision::MoveBlock >
template<>
struct DataType< ::hrca_decision::MoveBlockRequest>
{
  static const char* value()
  {
    return DataType< ::hrca_decision::MoveBlock >::value();
  }
  static const char* value(const ::hrca_decision::MoveBlockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrca_decision::MoveBlockResponse> should match
// service_traits::MD5Sum< ::hrca_decision::MoveBlock >
template<>
struct MD5Sum< ::hrca_decision::MoveBlockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrca_decision::MoveBlock >::value();
  }
  static const char* value(const ::hrca_decision::MoveBlockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrca_decision::MoveBlockResponse> should match
// service_traits::DataType< ::hrca_decision::MoveBlock >
template<>
struct DataType< ::hrca_decision::MoveBlockResponse>
{
  static const char* value()
  {
    return DataType< ::hrca_decision::MoveBlock >::value();
  }
  static const char* value(const ::hrca_decision::MoveBlockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRCA_DECISION_MESSAGE_MOVEBLOCK_H
