// Generated by gencpp from file hrca_decision/ResetRobot.msg
// DO NOT EDIT!


#ifndef HRCA_DECISION_MESSAGE_RESETROBOT_H
#define HRCA_DECISION_MESSAGE_RESETROBOT_H

#include <ros/service_traits.h>


#include <hrca_decision/ResetRobotRequest.h>
#include <hrca_decision/ResetRobotResponse.h>


namespace hrca_decision
{

struct ResetRobot
{

typedef ResetRobotRequest Request;
typedef ResetRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetRobot
} // namespace hrca_decision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrca_decision::ResetRobot > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hrca_decision::ResetRobot&) { return value(); }
};

template<>
struct DataType< ::hrca_decision::ResetRobot > {
  static const char* value()
  {
    return "hrca_decision/ResetRobot";
  }

  static const char* value(const ::hrca_decision::ResetRobot&) { return value(); }
};


// service_traits::MD5Sum< ::hrca_decision::ResetRobotRequest> should match
// service_traits::MD5Sum< ::hrca_decision::ResetRobot >
template<>
struct MD5Sum< ::hrca_decision::ResetRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrca_decision::ResetRobot >::value();
  }
  static const char* value(const ::hrca_decision::ResetRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrca_decision::ResetRobotRequest> should match
// service_traits::DataType< ::hrca_decision::ResetRobot >
template<>
struct DataType< ::hrca_decision::ResetRobotRequest>
{
  static const char* value()
  {
    return DataType< ::hrca_decision::ResetRobot >::value();
  }
  static const char* value(const ::hrca_decision::ResetRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrca_decision::ResetRobotResponse> should match
// service_traits::MD5Sum< ::hrca_decision::ResetRobot >
template<>
struct MD5Sum< ::hrca_decision::ResetRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrca_decision::ResetRobot >::value();
  }
  static const char* value(const ::hrca_decision::ResetRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrca_decision::ResetRobotResponse> should match
// service_traits::DataType< ::hrca_decision::ResetRobot >
template<>
struct DataType< ::hrca_decision::ResetRobotResponse>
{
  static const char* value()
  {
    return DataType< ::hrca_decision::ResetRobot >::value();
  }
  static const char* value(const ::hrca_decision::ResetRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRCA_DECISION_MESSAGE_RESETROBOT_H
