// Generated by gencpp from file hrca_msgs/GetRobotPoseRequest.msg
// DO NOT EDIT!


#ifndef HRCA_MSGS_MESSAGE_GETROBOTPOSEREQUEST_H
#define HRCA_MSGS_MESSAGE_GETROBOTPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrca_msgs
{
template <class ContainerAllocator>
struct GetRobotPoseRequest_
{
  typedef GetRobotPoseRequest_<ContainerAllocator> Type;

  GetRobotPoseRequest_()
    : frame()  {
    }
  GetRobotPoseRequest_(const ContainerAllocator& _alloc)
    : frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRobotPoseRequest_

typedef ::hrca_msgs::GetRobotPoseRequest_<std::allocator<void> > GetRobotPoseRequest;

typedef boost::shared_ptr< ::hrca_msgs::GetRobotPoseRequest > GetRobotPoseRequestPtr;
typedef boost::shared_ptr< ::hrca_msgs::GetRobotPoseRequest const> GetRobotPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator1> & lhs, const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.frame == rhs.frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator1> & lhs, const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrca_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a054304ca480f0e0c67ec5f261591b09";
  }

  static const char* value(const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa054304ca480f0e0ULL;
  static const uint64_t static_value2 = 0xc67ec5f261591b09ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrca_msgs/GetRobotPoseRequest";
  }

  static const char* value(const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string frame\n"
;
  }

  static const char* value(const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRobotPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrca_msgs::GetRobotPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRCA_MSGS_MESSAGE_GETROBOTPOSEREQUEST_H
