// Generated by gencpp from file hrca_msgs/GetRobotPose.msg
// DO NOT EDIT!


#ifndef HRCA_MSGS_MESSAGE_GETROBOTPOSE_H
#define HRCA_MSGS_MESSAGE_GETROBOTPOSE_H

#include <ros/service_traits.h>


#include <hrca_msgs/GetRobotPoseRequest.h>
#include <hrca_msgs/GetRobotPoseResponse.h>


namespace hrca_msgs
{

struct GetRobotPose
{

typedef GetRobotPoseRequest Request;
typedef GetRobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotPose
} // namespace hrca_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrca_msgs::GetRobotPose > {
  static const char* value()
  {
    return "374bd414473ccf176471f65d96682d5f";
  }

  static const char* value(const ::hrca_msgs::GetRobotPose&) { return value(); }
};

template<>
struct DataType< ::hrca_msgs::GetRobotPose > {
  static const char* value()
  {
    return "hrca_msgs/GetRobotPose";
  }

  static const char* value(const ::hrca_msgs::GetRobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::hrca_msgs::GetRobotPoseRequest> should match
// service_traits::MD5Sum< ::hrca_msgs::GetRobotPose >
template<>
struct MD5Sum< ::hrca_msgs::GetRobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrca_msgs::GetRobotPose >::value();
  }
  static const char* value(const ::hrca_msgs::GetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrca_msgs::GetRobotPoseRequest> should match
// service_traits::DataType< ::hrca_msgs::GetRobotPose >
template<>
struct DataType< ::hrca_msgs::GetRobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::hrca_msgs::GetRobotPose >::value();
  }
  static const char* value(const ::hrca_msgs::GetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrca_msgs::GetRobotPoseResponse> should match
// service_traits::MD5Sum< ::hrca_msgs::GetRobotPose >
template<>
struct MD5Sum< ::hrca_msgs::GetRobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrca_msgs::GetRobotPose >::value();
  }
  static const char* value(const ::hrca_msgs::GetRobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrca_msgs::GetRobotPoseResponse> should match
// service_traits::DataType< ::hrca_msgs::GetRobotPose >
template<>
struct DataType< ::hrca_msgs::GetRobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::hrca_msgs::GetRobotPose >::value();
  }
  static const char* value(const ::hrca_msgs::GetRobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRCA_MSGS_MESSAGE_GETROBOTPOSE_H
