// Generated by gencpp from file hrca_msgs/RobotTaskGoal.msg
// DO NOT EDIT!


#ifndef HRCA_MSGS_MESSAGE_ROBOTTASKGOAL_H
#define HRCA_MSGS_MESSAGE_ROBOTTASKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace hrca_msgs
{
template <class ContainerAllocator>
struct RobotTaskGoal_
{
  typedef RobotTaskGoal_<ContainerAllocator> Type;

  RobotTaskGoal_()
    : action()
    , pose1()
    , pose2()
    , object_name()  {
    }
  RobotTaskGoal_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , pose1(_alloc)
    , pose2(_alloc)
    , object_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose1_type;
  _pose1_type pose1;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose2_type;
  _pose2_type pose2;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;





  typedef boost::shared_ptr< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RobotTaskGoal_

typedef ::hrca_msgs::RobotTaskGoal_<std::allocator<void> > RobotTaskGoal;

typedef boost::shared_ptr< ::hrca_msgs::RobotTaskGoal > RobotTaskGoalPtr;
typedef boost::shared_ptr< ::hrca_msgs::RobotTaskGoal const> RobotTaskGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator1> & lhs, const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.pose1 == rhs.pose1 &&
    lhs.pose2 == rhs.pose2 &&
    lhs.object_name == rhs.object_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator1> & lhs, const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrca_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f2c64fd41eafea32d78342b5e64b8ad";
  }

  static const char* value(const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f2c64fd41eafea3ULL;
  static const uint64_t static_value2 = 0x2d78342b5e64b8adULL;
};

template<class ContainerAllocator>
struct DataType< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrca_msgs/RobotTaskGoal";
  }

  static const char* value(const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"string action #'hold', 'pick_and_place', 'move_to_pose', 'move_to_pose_cartesian', 'pick_and_handoff'\n"
"geometry_msgs/PoseStamped pose1\n"
"geometry_msgs/PoseStamped pose2\n"
"string object_name\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.pose1);
      stream.next(m.pose2);
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotTaskGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrca_msgs::RobotTaskGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrca_msgs::RobotTaskGoal_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "pose1: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose1);
    s << indent << "pose2: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose2);
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRCA_MSGS_MESSAGE_ROBOTTASKGOAL_H
