// Generated by gencpp from file hrca_msgs/RobotTaskResult.msg
// DO NOT EDIT!


#ifndef HRCA_MSGS_MESSAGE_ROBOTTASKRESULT_H
#define HRCA_MSGS_MESSAGE_ROBOTTASKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrca_msgs
{
template <class ContainerAllocator>
struct RobotTaskResult_
{
  typedef RobotTaskResult_<ContainerAllocator> Type;

  RobotTaskResult_()
    : success(false)  {
    }
  RobotTaskResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> const> ConstPtr;

}; // struct RobotTaskResult_

typedef ::hrca_msgs::RobotTaskResult_<std::allocator<void> > RobotTaskResult;

typedef boost::shared_ptr< ::hrca_msgs::RobotTaskResult > RobotTaskResultPtr;
typedef boost::shared_ptr< ::hrca_msgs::RobotTaskResult const> RobotTaskResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrca_msgs::RobotTaskResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrca_msgs::RobotTaskResult_<ContainerAllocator1> & lhs, const ::hrca_msgs::RobotTaskResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrca_msgs::RobotTaskResult_<ContainerAllocator1> & lhs, const ::hrca_msgs::RobotTaskResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrca_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hrca_msgs::RobotTaskResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrca_msgs/RobotTaskResult";
  }

  static const char* value(const ::hrca_msgs::RobotTaskResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"bool success\n"
;
  }

  static const char* value(const ::hrca_msgs::RobotTaskResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotTaskResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrca_msgs::RobotTaskResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrca_msgs::RobotTaskResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRCA_MSGS_MESSAGE_ROBOTTASKRESULT_H
