// Generated by gencpp from file hrca_msgs/RobotTaskFeedback.msg
// DO NOT EDIT!


#ifndef HRCA_MSGS_MESSAGE_ROBOTTASKFEEDBACK_H
#define HRCA_MSGS_MESSAGE_ROBOTTASKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrca_msgs
{
template <class ContainerAllocator>
struct RobotTaskFeedback_
{
  typedef RobotTaskFeedback_<ContainerAllocator> Type;

  RobotTaskFeedback_()
    : status()  {
    }
  RobotTaskFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct RobotTaskFeedback_

typedef ::hrca_msgs::RobotTaskFeedback_<std::allocator<void> > RobotTaskFeedback;

typedef boost::shared_ptr< ::hrca_msgs::RobotTaskFeedback > RobotTaskFeedbackPtr;
typedef boost::shared_ptr< ::hrca_msgs::RobotTaskFeedback const> RobotTaskFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator1> & lhs, const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator1> & lhs, const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrca_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrca_msgs/RobotTaskFeedback";
  }

  static const char* value(const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback, for now just return \"status\" e.g. 'running'\n"
"string status #'running'\n"
;
  }

  static const char* value(const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotTaskFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrca_msgs::RobotTaskFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRCA_MSGS_MESSAGE_ROBOTTASKFEEDBACK_H
