(cl:defpackage hrca_msgs-srv
  (:use )
  (:export
   "CLEAROCTOMAP"
   "<CLEAROCTOMAP-REQUEST>"
   "CLEAROCTOMAP-REQUEST"
   "<CLEAROCTOMAP-RESPONSE>"
   "CLEAROCTOMAP-RESPONSE"
   "GETROBOTPOSE"
   "<GETROBOTPOSE-REQUEST>"
   "GETROBOTPOSE-REQUEST"
   "<GETROBOTPOSE-RESPONSE>"
   "GETROBOTPOSE-RESPONSE"
   "MOVETOPOSE"
   "<MOVETOPOSE-REQUEST>"
   "MOVETOPOSE-REQUEST"
   "<MOVETOPOSE-RESPONSE>"
   "MOVETOPOSE-RESPONSE"
   "OBJECTDATAREQUEST"
   "<OBJECTDATAREQUEST-REQUEST>"
   "OBJECTDATAREQUEST-REQUEST"
   "<OBJECTDATAREQUEST-RESPONSE>"
   "OBJECTDATAREQUEST-RESPONSE"
  ))

