// Generated by gencpp from file cws_planning/MoveBlockResponse.msg
// DO NOT EDIT!


#ifndef CWS_PLANNING_MESSAGE_MOVEBLOCKRESPONSE_H
#define CWS_PLANNING_MESSAGE_MOVEBLOCKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cws_planning
{
template <class ContainerAllocator>
struct MoveBlockResponse_
{
  typedef MoveBlockResponse_<ContainerAllocator> Type;

  MoveBlockResponse_()
    : success(false)
    , temp(0)  {
    }
  MoveBlockResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , temp(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::cws_planning::MoveBlockResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cws_planning::MoveBlockResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveBlockResponse_

typedef ::cws_planning::MoveBlockResponse_<std::allocator<void> > MoveBlockResponse;

typedef boost::shared_ptr< ::cws_planning::MoveBlockResponse > MoveBlockResponsePtr;
typedef boost::shared_ptr< ::cws_planning::MoveBlockResponse const> MoveBlockResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cws_planning::MoveBlockResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cws_planning::MoveBlockResponse_<ContainerAllocator1> & lhs, const ::cws_planning::MoveBlockResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.temp == rhs.temp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cws_planning::MoveBlockResponse_<ContainerAllocator1> & lhs, const ::cws_planning::MoveBlockResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cws_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cws_planning::MoveBlockResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cws_planning::MoveBlockResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cws_planning::MoveBlockResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64379aa9ffbb0f8771915781c7d12eac";
  }

  static const char* value(const ::cws_planning::MoveBlockResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64379aa9ffbb0f87ULL;
  static const uint64_t static_value2 = 0x71915781c7d12eacULL;
};

template<class ContainerAllocator>
struct DataType< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cws_planning/MoveBlockResponse";
  }

  static const char* value(const ::cws_planning::MoveBlockResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"int32 temp\n"
"\n"
;
  }

  static const char* value(const ::cws_planning::MoveBlockResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveBlockResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cws_planning::MoveBlockResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cws_planning::MoveBlockResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "temp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CWS_PLANNING_MESSAGE_MOVEBLOCKRESPONSE_H
