// Generated by gencpp from file cws_planning/MoveToPosition.msg
// DO NOT EDIT!


#ifndef CWS_PLANNING_MESSAGE_MOVETOPOSITION_H
#define CWS_PLANNING_MESSAGE_MOVETOPOSITION_H

#include <ros/service_traits.h>


#include <cws_planning/MoveToPositionRequest.h>
#include <cws_planning/MoveToPositionResponse.h>


namespace cws_planning
{

struct MoveToPosition
{

typedef MoveToPositionRequest Request;
typedef MoveToPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToPosition
} // namespace cws_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cws_planning::MoveToPosition > {
  static const char* value()
  {
    return "40aca93d2ba3835d16d6b0bb93925874";
  }

  static const char* value(const ::cws_planning::MoveToPosition&) { return value(); }
};

template<>
struct DataType< ::cws_planning::MoveToPosition > {
  static const char* value()
  {
    return "cws_planning/MoveToPosition";
  }

  static const char* value(const ::cws_planning::MoveToPosition&) { return value(); }
};


// service_traits::MD5Sum< ::cws_planning::MoveToPositionRequest> should match
// service_traits::MD5Sum< ::cws_planning::MoveToPosition >
template<>
struct MD5Sum< ::cws_planning::MoveToPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cws_planning::MoveToPosition >::value();
  }
  static const char* value(const ::cws_planning::MoveToPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cws_planning::MoveToPositionRequest> should match
// service_traits::DataType< ::cws_planning::MoveToPosition >
template<>
struct DataType< ::cws_planning::MoveToPositionRequest>
{
  static const char* value()
  {
    return DataType< ::cws_planning::MoveToPosition >::value();
  }
  static const char* value(const ::cws_planning::MoveToPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cws_planning::MoveToPositionResponse> should match
// service_traits::MD5Sum< ::cws_planning::MoveToPosition >
template<>
struct MD5Sum< ::cws_planning::MoveToPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cws_planning::MoveToPosition >::value();
  }
  static const char* value(const ::cws_planning::MoveToPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cws_planning::MoveToPositionResponse> should match
// service_traits::DataType< ::cws_planning::MoveToPosition >
template<>
struct DataType< ::cws_planning::MoveToPositionResponse>
{
  static const char* value()
  {
    return DataType< ::cws_planning::MoveToPosition >::value();
  }
  static const char* value(const ::cws_planning::MoveToPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CWS_PLANNING_MESSAGE_MOVETOPOSITION_H
