// Generated by gencpp from file cws_planning/MoveBlock.msg
// DO NOT EDIT!


#ifndef CWS_PLANNING_MESSAGE_MOVEBLOCK_H
#define CWS_PLANNING_MESSAGE_MOVEBLOCK_H

#include <ros/service_traits.h>


#include <cws_planning/MoveBlockRequest.h>
#include <cws_planning/MoveBlockResponse.h>


namespace cws_planning
{

struct MoveBlock
{

typedef MoveBlockRequest Request;
typedef MoveBlockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveBlock
} // namespace cws_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cws_planning::MoveBlock > {
  static const char* value()
  {
    return "ce9e787312db48692e8fbbc8b03d8015";
  }

  static const char* value(const ::cws_planning::MoveBlock&) { return value(); }
};

template<>
struct DataType< ::cws_planning::MoveBlock > {
  static const char* value()
  {
    return "cws_planning/MoveBlock";
  }

  static const char* value(const ::cws_planning::MoveBlock&) { return value(); }
};


// service_traits::MD5Sum< ::cws_planning::MoveBlockRequest> should match
// service_traits::MD5Sum< ::cws_planning::MoveBlock >
template<>
struct MD5Sum< ::cws_planning::MoveBlockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cws_planning::MoveBlock >::value();
  }
  static const char* value(const ::cws_planning::MoveBlockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cws_planning::MoveBlockRequest> should match
// service_traits::DataType< ::cws_planning::MoveBlock >
template<>
struct DataType< ::cws_planning::MoveBlockRequest>
{
  static const char* value()
  {
    return DataType< ::cws_planning::MoveBlock >::value();
  }
  static const char* value(const ::cws_planning::MoveBlockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cws_planning::MoveBlockResponse> should match
// service_traits::MD5Sum< ::cws_planning::MoveBlock >
template<>
struct MD5Sum< ::cws_planning::MoveBlockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cws_planning::MoveBlock >::value();
  }
  static const char* value(const ::cws_planning::MoveBlockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cws_planning::MoveBlockResponse> should match
// service_traits::DataType< ::cws_planning::MoveBlock >
template<>
struct DataType< ::cws_planning::MoveBlockResponse>
{
  static const char* value()
  {
    return DataType< ::cws_planning::MoveBlock >::value();
  }
  static const char* value(const ::cws_planning::MoveBlockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CWS_PLANNING_MESSAGE_MOVEBLOCK_H
