// Generated by gencpp from file cws_planning/ResetRobot.msg
// DO NOT EDIT!


#ifndef CWS_PLANNING_MESSAGE_RESETROBOT_H
#define CWS_PLANNING_MESSAGE_RESETROBOT_H

#include <ros/service_traits.h>


#include <cws_planning/ResetRobotRequest.h>
#include <cws_planning/ResetRobotResponse.h>


namespace cws_planning
{

struct ResetRobot
{

typedef ResetRobotRequest Request;
typedef ResetRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetRobot
} // namespace cws_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cws_planning::ResetRobot > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::cws_planning::ResetRobot&) { return value(); }
};

template<>
struct DataType< ::cws_planning::ResetRobot > {
  static const char* value()
  {
    return "cws_planning/ResetRobot";
  }

  static const char* value(const ::cws_planning::ResetRobot&) { return value(); }
};


// service_traits::MD5Sum< ::cws_planning::ResetRobotRequest> should match
// service_traits::MD5Sum< ::cws_planning::ResetRobot >
template<>
struct MD5Sum< ::cws_planning::ResetRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cws_planning::ResetRobot >::value();
  }
  static const char* value(const ::cws_planning::ResetRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cws_planning::ResetRobotRequest> should match
// service_traits::DataType< ::cws_planning::ResetRobot >
template<>
struct DataType< ::cws_planning::ResetRobotRequest>
{
  static const char* value()
  {
    return DataType< ::cws_planning::ResetRobot >::value();
  }
  static const char* value(const ::cws_planning::ResetRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cws_planning::ResetRobotResponse> should match
// service_traits::MD5Sum< ::cws_planning::ResetRobot >
template<>
struct MD5Sum< ::cws_planning::ResetRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cws_planning::ResetRobot >::value();
  }
  static const char* value(const ::cws_planning::ResetRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cws_planning::ResetRobotResponse> should match
// service_traits::DataType< ::cws_planning::ResetRobot >
template<>
struct DataType< ::cws_planning::ResetRobotResponse>
{
  static const char* value()
  {
    return DataType< ::cws_planning::ResetRobot >::value();
  }
  static const char* value(const ::cws_planning::ResetRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CWS_PLANNING_MESSAGE_RESETROBOT_H
