// Generated by gencpp from file cws_planning/TrafficLight.msg
// DO NOT EDIT!


#ifndef CWS_PLANNING_MESSAGE_TRAFFICLIGHT_H
#define CWS_PLANNING_MESSAGE_TRAFFICLIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cws_planning
{
template <class ContainerAllocator>
struct TrafficLight_
{
  typedef TrafficLight_<ContainerAllocator> Type;

  TrafficLight_()
    : block_selected(0)
    , block_status(0)
    , zone_selected(0)
    , zone_status(0)  {
    }
  TrafficLight_(const ContainerAllocator& _alloc)
    : block_selected(0)
    , block_status(0)
    , zone_selected(0)
    , zone_status(0)  {
  (void)_alloc;
    }



   typedef int32_t _block_selected_type;
  _block_selected_type block_selected;

   typedef int32_t _block_status_type;
  _block_status_type block_status;

   typedef int32_t _zone_selected_type;
  _zone_selected_type zone_selected;

   typedef int32_t _zone_status_type;
  _zone_status_type zone_status;





  typedef boost::shared_ptr< ::cws_planning::TrafficLight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cws_planning::TrafficLight_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLight_

typedef ::cws_planning::TrafficLight_<std::allocator<void> > TrafficLight;

typedef boost::shared_ptr< ::cws_planning::TrafficLight > TrafficLightPtr;
typedef boost::shared_ptr< ::cws_planning::TrafficLight const> TrafficLightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cws_planning::TrafficLight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cws_planning::TrafficLight_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cws_planning::TrafficLight_<ContainerAllocator1> & lhs, const ::cws_planning::TrafficLight_<ContainerAllocator2> & rhs)
{
  return lhs.block_selected == rhs.block_selected &&
    lhs.block_status == rhs.block_status &&
    lhs.zone_selected == rhs.zone_selected &&
    lhs.zone_status == rhs.zone_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cws_planning::TrafficLight_<ContainerAllocator1> & lhs, const ::cws_planning::TrafficLight_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cws_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cws_planning::TrafficLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cws_planning::TrafficLight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cws_planning::TrafficLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cws_planning::TrafficLight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cws_planning::TrafficLight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cws_planning::TrafficLight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cws_planning::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5a4682048736e7ecf53045e87035b77";
  }

  static const char* value(const ::cws_planning::TrafficLight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5a4682048736e7eULL;
  static const uint64_t static_value2 = 0xcf53045e87035b77ULL;
};

template<class ContainerAllocator>
struct DataType< ::cws_planning::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cws_planning/TrafficLight";
  }

  static const char* value(const ::cws_planning::TrafficLight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cws_planning::TrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 block_selected\n"
"int32 block_status\n"
"int32 zone_selected\n"
"int32 zone_status\n"
;
  }

  static const char* value(const ::cws_planning::TrafficLight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cws_planning::TrafficLight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.block_selected);
      stream.next(m.block_status);
      stream.next(m.zone_selected);
      stream.next(m.zone_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cws_planning::TrafficLight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cws_planning::TrafficLight_<ContainerAllocator>& v)
  {
    s << indent << "block_selected: ";
    Printer<int32_t>::stream(s, indent + "  ", v.block_selected);
    s << indent << "block_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.block_status);
    s << indent << "zone_selected: ";
    Printer<int32_t>::stream(s, indent + "  ", v.zone_selected);
    s << indent << "zone_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.zone_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CWS_PLANNING_MESSAGE_TRAFFICLIGHT_H
