(cl:defpackage hrca_msgs-msg
  (:use )
  (:export
   "<ROBOTTASKACTION>"
   "ROBOTTASKACTION"
   "<ROBOTTASKACTIONFEEDBACK>"
   "ROBOTTASKACTIONFEEDBACK"
   "<ROBOTTASKACTIONGOAL>"
   "ROBOTTASKACTIONGOAL"
   "<ROBOTTASKACTIONRESULT>"
   "ROBOTTASKACTIONRESULT"
   "<ROBOTTASKFEEDBACK>"
   "ROBOTTASKFEEDBACK"
   "<ROBOTTASKGOAL>"
   "ROBOTTASKGOAL"
   "<ROBOTTASKRESULT>"
   "ROBOTTASKRESULT"
  ))

