; Auto-generated. Do not edit!


(cl:in-package hrca_msgs-msg)


;//! \htmlinclude RobotTaskFeedback.msg.html

(cl:defclass <RobotTaskFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:string
    :initform ""))
)

(cl:defclass RobotTaskFeedback (<RobotTaskFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RobotTaskFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RobotTaskFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hrca_msgs-msg:<RobotTaskFeedback> is deprecated: use hrca_msgs-msg:RobotTaskFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <RobotTaskFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hrca_msgs-msg:status-val is deprecated.  Use hrca_msgs-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RobotTaskFeedback>) ostream)
  "Serializes a message object of type '<RobotTaskFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RobotTaskFeedback>) istream)
  "Deserializes a message object of type '<RobotTaskFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RobotTaskFeedback>)))
  "Returns string type for a message object of type '<RobotTaskFeedback>"
  "hrca_msgs/RobotTaskFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RobotTaskFeedback)))
  "Returns string type for a message object of type 'RobotTaskFeedback"
  "hrca_msgs/RobotTaskFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RobotTaskFeedback>)))
  "Returns md5sum for a message object of type '<RobotTaskFeedback>"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RobotTaskFeedback)))
  "Returns md5sum for a message object of type 'RobotTaskFeedback"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RobotTaskFeedback>)))
  "Returns full string definition for message of type '<RobotTaskFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback, for now just return \"status\" e.g. 'running'~%string status #'running'~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RobotTaskFeedback)))
  "Returns full string definition for message of type 'RobotTaskFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback, for now just return \"status\" e.g. 'running'~%string status #'running'~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RobotTaskFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RobotTaskFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RobotTaskFeedback
    (cl:cons ':status (status msg))
))
